# Generated by Django 2.2.1 on 2020-01-03 21:58

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_cleanreviewmodel_masteraddmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleLocationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('perfect_for', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Great breakfast', 'Great breakfast'), ('On-the-run', 'On-the-run'), ('Last-min dinner', 'Last-min dinner'), ('Impressing guests', 'Impressing guests'), ('Date night', 'Date night'), ('Big group', 'Big group'), ('Peace & quiet', 'Peace & quiet'), ('Living large', 'Living large'), ('Sunny days', 'Sunny days')], max_length=119, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('category1', models.CharField(blank=True, max_length=30, null=True)),
                ('category2', models.CharField(blank=True, max_length=30, null=True)),
                ('category3', models.CharField(blank=True, max_length=30, null=True)),
                ('postcode', models.CharField(blank=True, max_length=30, null=True)),
                ('suburb', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('count_ratings', models.IntegerField(blank=True, null=True)),
                ('count_wishlist', models.IntegerField(blank=True, null=True)),
                ('ave_ratings', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
            ],
        ),
    ]
