# Generated by Django 2.2.1 on 2020-01-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200104_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteraddmodel',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True),
        ),
    ]
