# Generated by Django 2.2.1 on 2020-01-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200112_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleanreviewmodel',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='singlelocationrecord',
            name='temperature',
        ),
    ]
