# Generated by Django 2.2.1 on 2020-01-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_betafeedbackmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleanreviewmodel',
            name='ave_rating',
        ),
        migrations.RemoveField(
            model_name='cleanreviewmodel',
            name='count_rating',
        ),
        migrations.AddField(
            model_name='cleanreviewmodel',
            name='lat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cleanreviewmodel',
            name='long',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
