# Generated by Django 2.2.1 on 2020-02-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=35, null=True)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('image_link', models.CharField(max_length=200, null=True)),
                ('trigger_min', models.IntegerField(blank=True, null=True)),
                ('trigger_max', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
