# Generated by Django 2.2.1 on 2020-02-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='X_checkboxtest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkbox1', models.BooleanField(default=False)),
                ('checkbox2', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='cleanreviewmodel',
            name='perfect_for',
        ),
        migrations.RemoveField(
            model_name='masteraddmodel',
            name='perfect_for',
        ),
        migrations.RemoveField(
            model_name='singlelocationrecord',
            name='perfect_for',
        ),
        migrations.AddField(
            model_name='cleanreviewmodel',
            name='pf_big_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cleanreviewmodel',
            name='pf_breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cleanreviewmodel',
            name='pf_date_night',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cleanreviewmodel',
            name='pf_impressing_guests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cleanreviewmodel',
            name='pf_last_min_dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cleanreviewmodel',
            name='pf_living_large',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cleanreviewmodel',
            name='pf_peace_quiet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cleanreviewmodel',
            name='pf_quick_lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cleanreviewmodel',
            name='pf_sunny_days',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masteraddmodel',
            name='pf_big_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masteraddmodel',
            name='pf_breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masteraddmodel',
            name='pf_date_night',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masteraddmodel',
            name='pf_impressing_guests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masteraddmodel',
            name='pf_last_min_dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masteraddmodel',
            name='pf_living_large',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masteraddmodel',
            name='pf_peace_quiet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masteraddmodel',
            name='pf_quick_lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masteraddmodel',
            name='pf_sunny_days',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singlelocationrecord',
            name='pf_big_group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singlelocationrecord',
            name='pf_breakfast',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singlelocationrecord',
            name='pf_date_night',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singlelocationrecord',
            name='pf_impressing_guests',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singlelocationrecord',
            name='pf_last_min_dinner',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singlelocationrecord',
            name='pf_living_large',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singlelocationrecord',
            name='pf_peace_quiet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singlelocationrecord',
            name='pf_quick_lunch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singlelocationrecord',
            name='pf_sunny_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
